# Generated by Django 4.0.2 on 2022-02-01 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='translate',
            new_name='tarjima',
        ),
    ]
